// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldItemHandle : RemoteTableHandle<EventContext, WorldItem>
        {
            protected override string RemoteTableName => "world_item";

            public sealed class ItemIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(WorldItem row) => row.ItemId;

                public ItemIdUniqueIndex(WorldItemHandle table) : base(table) { }
            }

            public readonly ItemIdUniqueIndex ItemId;

            internal WorldItemHandle(DbConnection conn) : base(conn)
            {
                ItemId = new(this);
            }

            protected override object GetPrimaryKey(WorldItem row) => row.ItemId;
        }

        public readonly WorldItemHandle WorldItem;
    }
}
