// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class InventoryItem
    {
        [DataMember(Name = "PlayerId")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "ItemType")]
        public string ItemType;
        [DataMember(Name = "Quantity")]
        public int Quantity;
        [DataMember(Name = "SlotIndex")]
        public int SlotIndex;

        public InventoryItem(
            SpacetimeDB.Identity PlayerId,
            string ItemType,
            int Quantity,
            int SlotIndex
        )
        {
            this.PlayerId = PlayerId;
            this.ItemType = ItemType;
            this.Quantity = Quantity;
            this.SlotIndex = SlotIndex;
        }

        public InventoryItem()
        {
            this.ItemType = "";
        }
    }
}
