// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "DisplayName")]
        public string DisplayName;
        [DataMember(Name = "PositionX")]
        public float PositionX;
        [DataMember(Name = "PositionY")]
        public float PositionY;
        [DataMember(Name = "Online")]
        public bool Online;

        public Player(
            SpacetimeDB.Identity Identity,
            string DisplayName,
            float PositionX,
            float PositionY,
            bool Online
        )
        {
            this.Identity = Identity;
            this.DisplayName = DisplayName;
            this.PositionX = PositionX;
            this.PositionY = PositionY;
            this.Online = Online;
        }

        public Player()
        {
            this.DisplayName = "";
        }
    }
}
