// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldItem
    {
        [DataMember(Name = "ItemId")]
        public uint ItemId;
        [DataMember(Name = "ItemType")]
        public string ItemType;
        [DataMember(Name = "PositionX")]
        public float PositionX;
        [DataMember(Name = "PositionY")]
        public float PositionY;
        [DataMember(Name = "StackSize")]
        public int StackSize;

        public WorldItem(
            uint ItemId,
            string ItemType,
            float PositionX,
            float PositionY,
            int StackSize
        )
        {
            this.ItemId = ItemId;
            this.ItemType = ItemType;
            this.PositionX = PositionX;
            this.PositionY = PositionY;
            this.StackSize = StackSize;
        }

        public WorldItem()
        {
            this.ItemType = "";
        }
    }
}
