// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ResetWorldHandler(ReducerEventContext ctx);
        public event ResetWorldHandler? OnResetWorld;

        public void ResetWorld()
        {
            conn.InternalCallReducer(new Reducer.ResetWorld(), this.SetCallReducerFlags.ResetWorldFlags);
        }

        public bool InvokeResetWorld(ReducerEventContext ctx, Reducer.ResetWorld args)
        {
            if (OnResetWorld == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnResetWorld(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ResetWorld : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "ResetWorld";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ResetWorldFlags;
        public void ResetWorld(CallReducerFlags flags) => ResetWorldFlags = flags;
    }
}
