// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetDisplayNameHandler(ReducerEventContext ctx, string name);
        public event SetDisplayNameHandler? OnSetDisplayName;

        public void SetDisplayName(string name)
        {
            conn.InternalCallReducer(new Reducer.SetDisplayName(name), this.SetCallReducerFlags.SetDisplayNameFlags);
        }

        public bool InvokeSetDisplayName(ReducerEventContext ctx, Reducer.SetDisplayName args)
        {
            if (OnSetDisplayName == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetDisplayName(
                ctx,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetDisplayName : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;

            public SetDisplayName(string Name)
            {
                this.Name = Name;
            }

            public SetDisplayName()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "SetDisplayName";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetDisplayNameFlags;
        public void SetDisplayName(CallReducerFlags flags) => SetDisplayNameFlags = flags;
    }
}
