// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdatePositionHandler(ReducerEventContext ctx, float x, float y);
        public event UpdatePositionHandler? OnUpdatePosition;

        public void UpdatePosition(float x, float y)
        {
            conn.InternalCallReducer(new Reducer.UpdatePosition(x, y), this.SetCallReducerFlags.UpdatePositionFlags);
        }

        public bool InvokeUpdatePosition(ReducerEventContext ctx, Reducer.UpdatePosition args)
        {
            if (OnUpdatePosition == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdatePosition(
                ctx,
                args.X,
                args.Y
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdatePosition : Reducer, IReducerArgs
        {
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;

            public UpdatePosition(
                float X,
                float Y
            )
            {
                this.X = X;
                this.Y = Y;
            }

            public UpdatePosition()
            {
            }

            string IReducerArgs.ReducerName => "UpdatePosition";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdatePositionFlags;
        public void UpdatePosition(CallReducerFlags flags) => UpdatePositionFlags = flags;
    }
}
